<revisionlist>
  <revision rev="1" vrev="1">
    <srcmd5>6cc8e428af9ada4b7160b6d7cbf0ae2f</srcmd5>
    <version>0.2.1</version>
    <time>1567092357</time>
    <user>dimstar_suse</user>
    <comment> </comment>
    <requestid>726870</requestid>
  </revision>
  <revision rev="2" vrev="1">
    <srcmd5>a3a90bf0345268cda818b9b621ad89b3</srcmd5>
    <version>0.3.0</version>
    <time>1582207069</time>
    <user>dimstar_suse</user>
    <comment>- Update to 0.3.0:
  * subtests now correctly captures and displays stdout/stderr (#18).</comment>
    <requestid>777568</requestid>
  </revision>
  <revision rev="3" vrev="1">
    <srcmd5>00b628172a6865a0ec60fa89903dbfbd</srcmd5>
    <version>0.3.1</version>
    <time>1591742950</time>
    <user>dimstar_suse</user>
    <comment>- Update to 0.3.1:
  * Fix pytest 5.4 support.</comment>
    <requestid>812805</requestid>
  </revision>
</revisionlist>
