<revisionlist>
  <revision rev="1" vrev="1">
    <srcmd5>89cc69c26e8627286900855b1b5c5c5f</srcmd5>
    <version>1.2</version>
    <time>1559375086</time>
    <user>dimstar_suse</user>
    <comment></comment>
    <requestid>703205</requestid>
  </revision>
  <revision rev="2" vrev="1">
    <srcmd5>24d2c65c93f8a5baeff635c17ea35bdc</srcmd5>
    <version>1.3</version>
    <time>1560800089</time>
    <user>dimstar_suse</user>
    <comment>- Update to 1.3:
  * Fixed a bug in the tmpfs.py and passthroughfs.py example file systems</comment>
    <requestid>710356</requestid>
  </revision>
  <revision rev="3" vrev="1">
    <srcmd5>a79c9f011bc6fe4dac13c416ecc4b8d7</srcmd5>
    <version>1.3.1</version>
    <time>1563914265</time>
    <user>dimstar_suse</user>
    <comment>- Update to 1.3.1:
  *  Fixed a bug in the :file:`hello_asyncio.py` example.</comment>
    <requestid>717803</requestid>
  </revision>
  <revision rev="4" vrev="1">
    <srcmd5>2f24f37ab252f818e6a20fc4fd02abd2</srcmd5>
    <version>2.0.0</version>
    <time>1570701213</time>
    <user>dimstar_suse</user>
    <comment>- Update to 2.0.0:
  * Changed open handler to return the new FileInfo struct to allow
    for modification of certain kernel file attributes, e.g. direct_io.</comment>
    <requestid>736804</requestid>
  </revision>
  <revision rev="5" vrev="1">
    <srcmd5>5aa2a53938d8dad7cc938fe841c8eeb4</srcmd5>
    <version>3.0.0</version>
    <time>1597403442</time>
    <user>dimstar_suse</user>
    <comment></comment>
    <requestid>824896</requestid>
  </revision>
  <revision rev="6" vrev="2">
    <srcmd5>d33d1a4ae1106d175997b6814867cf69</srcmd5>
    <version>3.0.0</version>
    <time>1615905948</time>
    <user>RBrownSUSE</user>
    <comment>- Add fix_catch_log_handler.patch to make tests compatible with
  pytest &gt;= 6.0.0, which removed never documented attribute
  .catch_log_handler of log item (gh#libfuse/pyfuse3#27).
</comment>
    <requestid>879272</requestid>
  </revision>
  <revision rev="7" vrev="1">
    <srcmd5>f5b9c2a56813cc65c682cec2a1f76fe9</srcmd5>
    <version>3.2.0</version>
    <time>1621201316</time>
    <user>dimstar_suse</user>
    <comment></comment>
    <requestid>893447</requestid>
  </revision>
  <revision rev="8" vrev="2">
    <srcmd5>2c1765ea35a3413d43379e03e5b318cc</srcmd5>
    <version>3.2.0</version>
    <time>1621269932</time>
    <user>dimstar_suse</user>
    <comment></comment>
    <requestid>893734</requestid>
  </revision>
  <revision rev="9" vrev="1">
    <srcmd5>f1aca3b29f42dc718731bfb923e66096</srcmd5>
    <version>3.2.2</version>
    <time>1673209538</time>
    <user>dimstar_suse</user>
    <comment>- update to 3.2.2:
  * remove support for python 3.5 (broken, out of support by python devs)
  * cythonize with latest Cython 0.29.x (brings Python 3.11 support)
  * use github actions for CI, remove travis-ci
  * update README: minimal maintenance, not developed
  * update setup.py with tested python versions
  * examples/tmpfs.py: work around strange kernel behaviour (calling SETATTR
    after
  UNLINK of a (not open) file): respond with ENOENT instead of crashing.
  * Add type annotations
  * Passing a XATTR_CREATE or XATTR_REPLACE to setxattr() is now working
  correctly.
- drop 0001-timestamp-rounding-tests-avoid-y2038-issue.patch (upstream)</comment>
    <requestid>1056834</requestid>
  </revision>
  <revision rev="10" vrev="1">
    <srcmd5>f8b68f02fb391c919844ac5dba4c48fb</srcmd5>
    <version>3.2.3</version>
    <time>1685632796</time>
    <user>dimstar_suse</user>
    <comment>- update to 3.2.3:
  * cythonize with latest Cython 0.29.34 (brings Python 3.12
    support)
  * add a minimal pyproject.toml, require setuptools
  * tests: fix integer overflow on 32-bit arches, fixes #47
  * test: Use shutil.which() instead of external which(1) program
  * setup.py: catch more generic OSError when searching Cython,
    fixes #63
  * setup.py: require Cython &gt;= 0.29
  * fix basedir computation in setup.py (fix pip install -e .)
  * use sphinx &lt; 6.0 due to compatibility issues with more recent
    versions</comment>
    <requestid>1090226</requestid>
  </revision>
  <revision rev="11" vrev="1">
    <srcmd5>78b539f61e29cec339608042275096c1</srcmd5>
    <version>3.3.0</version>
    <time>1692045335</time>
    <user>dimstar_suse</user>
    <comment>- update to 3.3.0:
  * Cythonized with latest Cython 3.0.0.
  * Drop Python 3.6 and 3.7 support and testing, #71.
  * CI: also test python 3.12. test on cython 0.29 and cython
    3.0.
  * Tell Cython that callbacks may raise exceptions, #80.
  * Fix lookup in examples/hello.py, similar to #16.
  * Misc. CI, testing, build and sphinx related fixes.</comment>
    <requestid>1103738</requestid>
  </revision>
  <revision rev="12" vrev="1">
    <srcmd5>bad265a78cffc0cf99af90b51b8886d0</srcmd5>
    <version>3.4.0</version>
    <time>1725448954</time>
    <user>dimstar_suse</user>
    <comment>- update to 3.4.0:
  * Cythonized with latest Cython 3.0.11 to support Python 3.13.
  * CI: also test python 3.13, run mypy.
  * Move _pyfuse3 to pyfuse3._pyfuse3 and add a compatibility
    wrapper for the old name.
  * Move pyfuse3_asyncio to pyfuse3.asyncio and add a
    compatibility wrapper for the old name.
  * Add bytes subclass XAttrNameT as the type of extended
    attribute names.
  * Various fixes to type annotations.
  * Add py.typed marker to enable external use of type
    annotations.</comment>
    <requestid>1198048</requestid>
  </revision>
</revisionlist>
